### ISSUE TITLE
Conflict with babel-french commands

### ISSUE THREAD

**Issue by yguilhem** [pgf-tikz/pgf-pie#1]
The redefinition of `\scalefont` command changes the result of babel-french commands `\ier` and `\ieme`, based on `\up{...}` command. Here is a MWE.
```
\documentclass[french]{article}
\usepackage[T1]{fontenc}
\usepackage{babel}
\usepackage{pgf-pie} % loading it or not -> it will change the superscripts position
\begin{document}
1\ier{} 2\ieme{} 3\up{e}
\end{document}
```
Maybe instead of redefining `\scalefont` command, it is possible to define a new `\pgfpie@scalefont` command and use it in place of `\scalefont` inside the `pgf-pie` package?
I tested it and it solved my problem, but it might bring other issues with `pgf-pie` features.

PS : I also opened an issue on the original project https://github.com/xuyuan/pgf-pie/issues/16

**Comment by pcotret** [comment]
As soon as I have the `french` option for babel, I can see a kind of angle value in my pie charts
![image](https://user-images.githubusercontent.com/404135/94373591-a8e5dc00-0106-11eb-8e87-b52b330e64e3.png)

PS : found a fix on Stackoverflow, just added the following line in my preamble:
```tex
\usetikzlibrary{babel}
```
(source: https://tex.stackexchange.com/questions/256612/pgf-pie-and-babel-incompatibility?noredirect=1&lq=1)

**Comment by JeromeSi** [comment]
Thanks pcotret, I'm using 
`\usepackage{pgf-pie}
\usetikzlibrary{babel}`
and all is ok
