### ISSUE TITLE
Numbertext clash with Babel Tikzlibrary

### ISSUE THREAD

**Issue by Pazukulele** [pgf-tikz/pgf-pie#10]
Using square mode (and only then) after loading the babel tikzlibrary produces an "Undefined control sequence" error. Instead of, e.g., "6", output is "@numbertext 6".

**Comment by hmenke** [comment]
Please provide a MWE.

**Comment by Pazukulele** [comment]
```latex
\documentclass[border = 10pt]{standalone}
\usepackage{tikz}
\usetikzlibrary{
	babel
}
\usepackage{pgf-pie}

\begin{document}
\begin{tikzpicture}
  \pie [square,scale font,
        color = {blue!10, blue!20, blue!40}]
    { 62/\TeX\ Live and Mac\TeX,
      32/MiK\TeX\ and Pro\TeX t, 6/Other \TeX }
\end{tikzpicture}
\end{document}
```

**Comment by hmenke** [comment]
I see, when `babel` is active `\scantokens` is run on the node text. The node text contains things like `\pgfpie@scalefont` but the catcode of `@` is reset to 12 which then blows up with
```
! Undefined control sequence.
l.1 \pgfpie
```
