### ISSUE TITLE
How to use pgf-pie with CSV files?

### ISSUE THREAD

**Issue by Garfield96** [pgf-tikz/pgf-pie#12]
Using CSV files as input for charts is useful if data changes frequently. Unfortunately, I wasn't able to set up pgf-pie with CSV input. There is a related answer on Stackexchange [https://tex.stackexchange.com/a/461026](https://tex.stackexchange.com/a/461026), but this answer neither imports labels from CSV nor does it automatically adjust to different numbers of sectors.

My current solution is to use the following command to transform the CSV file into a valid input string and then copy this string into the `pie` command:
```tex
\csvloop{file={"<filename>.csv"}, column names={Type=\Type,Percentage=\Percentage}, before line={,}, command={{\Percentage /\Type}}}
```
Using this command directly inside the pie command does not work.

Is there a better way of using CSV input?

**Comment by hmenke** [comment]
This doesn't really look like a bug report.  If you have questions about how to use pgf-pie, I'd like to kindly refer you to https://tex.stackexchange.com/ which is much better suited for Q&A.

**Comment by Garfield96** [comment]
Thanks for the quick reply. You are right, this is not a bug report. I wasn't sure whether this is a question or a feature request. 
In case it is already possible to do this, it would be nice to have this described in the official documentation. If it is not possible with the current implementation, please view this issue as a feature request. Since both cases require changes to the source, I decided to open an issue instead of asking on Stackexchange.

**Comment by hmenke** [comment]
Processing CSV data is beyond the scope of pgf-pie, sorry. There are multiple packages that can read CSV files and transform the data into something that can be used with PGF's `\foreach` loop (which is what pgf-pie uses internally).
