### ISSUE TITLE
Feature request: A `hide text` option

### ISSUE THREAD

**Issue by briochemc** [pgf-tikz/pgf-pie#5]
Just like the `hide number`, but for text.

**Comment by muzimuzhi** [comment]
A first try: https://github.com/muzimuzhi/pgf-pie/tree/feature-hide-label, noted the new option is named `hide label`, rather than `hide text`.

Some tests:
```tex
\documentclass[twocolumn]{article}
\usepackage[scale=.9]{geometry}
\usepackage{pgf-pie}

\begin{document}
\pgfkeys{every pie/.style={radius=1}}

\newcommand\testPgfPie[1]{
  \foreach \i in {label,pin,inside,legend} {
    \pgfkeys{every pie/.append style/.expanded={#1,text=\i}}
    
    \begin{tikzpicture}
      \pie {10/A, 20/B, 30/C, 40/D}
      \pie[pos={3,0}, hide number] {10/A, 20/B, 30/C, 40/D}
      \pie[pos={6,0}, hide label] {10/A, 20/B, 30/C, 40/D}
    \end{tikzpicture}\par
  }
}

\testPgfPie{}
\testPgfPie{polar}  \newpage
\testPgfPie{square}
\testPgfPie{cloud}
\end{document}
```
![image](https://user-images.githubusercontent.com/6376638/97275879-751ae500-1871-11eb-9147-a4a1c0f3af4f.png)

**Comment by briochemc** [comment]
This looks great!

**Comment by hmenke** [comment]
@muzimuzhi I started rewriting `pgf-pie`.  Sorry for the trouble, but you will have to rewrite the code.  A simple rebase won't do this time.

**Comment by muzimuzhi** [comment]
@hmenke Never mind. Rewriting has higher precedence than every patching/extension else.
