### ISSUE TITLE
'polar' breaks with non-integer fraction

### ISSUE THREAD

**Issue by PhelypeOleinik** [pgf-tikz/pgf-pie#6]
The `polar` option expects the fractions of the pie to be integers when surveying the maximum value:
```latex
  \xdef\maxValue{0}
  \foreach \p/\e in {#2} {
    \ifnum \maxValue < \p
    \xdef\maxValue{\p}
    \fi
  }
```
which breaks with non-integers:
```latex
\documentclass{article}
\usepackage{pgf-pie}
\begin{document}
\begin{tikzpicture}
  \pie[polar]{10.2/Nuclear, 15.8/Hydro, 9.8/Renewables, 38.2/Coal, 2.9/Oil, 23.1/Natural gas}
\end{tikzpicture}
\end{document}
```

A quick fix is to use `\ifdim` instead:
```latex
  \xdef\maxValue{0}
  \foreach \p/\e in {#2} {
    \ifdim \maxValue pt < \p pt
    \xdef\maxValue{\p}
    \fi
  }
```

**Comment by muzimuzhi** [comment]
Related source lines
https://github.com/pgf-tikz/pgf-pie/blob/d3bf8967d629ca72789f3542849e8cb57dfd3f85/tex/latex/pgf-pie/pgf-pie.sty#L385-L389

As hmenke pointed out in https://github.com/pgf-tikz/pgf-pie/pull/3#issuecomment-738928964,

> This whole package really just needs a rewrite as a proper TikZ library.
